//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebservices_Wpf.LogfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ProjectWebservices_Wcf")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AfdelingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlarmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoligField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Afdeling {
            get {
                return this.AfdelingField;
            }
            set {
                if ((object.ReferenceEquals(this.AfdelingField, value) != true)) {
                    this.AfdelingField = value;
                    this.RaisePropertyChanged("Afdeling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alarm {
            get {
                return this.AlarmField;
            }
            set {
                if ((object.ReferenceEquals(this.AlarmField, value) != true)) {
                    this.AlarmField = value;
                    this.RaisePropertyChanged("Alarm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bolig {
            get {
                return this.BoligField;
            }
            set {
                if ((object.ReferenceEquals(this.BoligField, value) != true)) {
                    this.BoligField = value;
                    this.RaisePropertyChanged("Bolig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Logfile", Namespace="http://schemas.datacontract.org/2004/07/ProjectWebservices_Wcf")]
    [System.SerializableAttribute()]
    public partial class Logfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AfdelingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime AfmeldtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlarmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BoligField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NavnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Afdeling {
            get {
                return this.AfdelingField;
            }
            set {
                if ((object.ReferenceEquals(this.AfdelingField, value) != true)) {
                    this.AfdelingField = value;
                    this.RaisePropertyChanged("Afdeling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Afmeldt {
            get {
                return this.AfmeldtField;
            }
            set {
                if ((this.AfmeldtField.Equals(value) != true)) {
                    this.AfmeldtField = value;
                    this.RaisePropertyChanged("Afmeldt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alarm {
            get {
                return this.AlarmField;
            }
            set {
                if ((object.ReferenceEquals(this.AlarmField, value) != true)) {
                    this.AlarmField = value;
                    this.RaisePropertyChanged("Alarm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bolig {
            get {
                return this.BoligField;
            }
            set {
                if ((object.ReferenceEquals(this.BoligField, value) != true)) {
                    this.BoligField = value;
                    this.RaisePropertyChanged("Bolig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Navn {
            get {
                return this.NavnField;
            }
            set {
                if ((object.ReferenceEquals(this.NavnField, value) != true)) {
                    this.NavnField = value;
                    this.RaisePropertyChanged("Navn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Tid {
            get {
                return this.TidField;
            }
            set {
                if ((this.TidField.Equals(value) != true)) {
                    this.TidField = value;
                    this.RaisePropertyChanged("Tid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogfileService.ILogfileService")]
    public interface ILogfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/Log", ReplyAction="http://tempuri.org/ILogfileService/LogResponse")]
        ProjectWebservices_Wpf.LogfileService.CompositeType Log(ProjectWebservices_Wpf.LogfileService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/Log", ReplyAction="http://tempuri.org/ILogfileService/LogResponse")]
        System.Threading.Tasks.Task<ProjectWebservices_Wpf.LogfileService.CompositeType> LogAsync(ProjectWebservices_Wpf.LogfileService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/ReadLogfiles", ReplyAction="http://tempuri.org/ILogfileService/ReadLogfilesResponse")]
        ProjectWebservices_Wpf.LogfileService.Logfile[] ReadLogfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/ReadLogfiles", ReplyAction="http://tempuri.org/ILogfileService/ReadLogfilesResponse")]
        System.Threading.Tasks.Task<ProjectWebservices_Wpf.LogfileService.Logfile[]> ReadLogfilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/DisposeAlarm", ReplyAction="http://tempuri.org/ILogfileService/DisposeAlarmResponse")]
        bool DisposeAlarm(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/DisposeAlarm", ReplyAction="http://tempuri.org/ILogfileService/DisposeAlarmResponse")]
        System.Threading.Tasks.Task<bool> DisposeAlarmAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogfileServiceChannel : ProjectWebservices_Wpf.LogfileService.ILogfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogfileServiceClient : System.ServiceModel.ClientBase<ProjectWebservices_Wpf.LogfileService.ILogfileService>, ProjectWebservices_Wpf.LogfileService.ILogfileService {
        
        public LogfileServiceClient() {
        }
        
        public LogfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjectWebservices_Wpf.LogfileService.CompositeType Log(ProjectWebservices_Wpf.LogfileService.CompositeType composite) {
            return base.Channel.Log(composite);
        }
        
        public System.Threading.Tasks.Task<ProjectWebservices_Wpf.LogfileService.CompositeType> LogAsync(ProjectWebservices_Wpf.LogfileService.CompositeType composite) {
            return base.Channel.LogAsync(composite);
        }
        
        public ProjectWebservices_Wpf.LogfileService.Logfile[] ReadLogfiles() {
            return base.Channel.ReadLogfiles();
        }
        
        public System.Threading.Tasks.Task<ProjectWebservices_Wpf.LogfileService.Logfile[]> ReadLogfilesAsync() {
            return base.Channel.ReadLogfilesAsync();
        }
        
        public bool DisposeAlarm(string id) {
            return base.Channel.DisposeAlarm(id);
        }
        
        public System.Threading.Tasks.Task<bool> DisposeAlarmAsync(string id) {
            return base.Channel.DisposeAlarmAsync(id);
        }
    }
}
