//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectWebservices_Console.LogfileService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Logfile", Namespace="http://schemas.datacontract.org/2004/07/ProjectWebservices_Azure_Pub")]
    [System.SerializableAttribute()]
    public partial class Logfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlarmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DisposedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Alarm {
            get {
                return this.AlarmField;
            }
            set {
                if ((object.ReferenceEquals(this.AlarmField, value) != true)) {
                    this.AlarmField = value;
                    this.RaisePropertyChanged("Alarm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apartment {
            get {
                return this.ApartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartmentField, value) != true)) {
                    this.ApartmentField = value;
                    this.RaisePropertyChanged("Apartment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Department {
            get {
                return this.DepartmentField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentField, value) != true)) {
                    this.DepartmentField = value;
                    this.RaisePropertyChanged("Department");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Disposed {
            get {
                return this.DisposedField;
            }
            set {
                if ((this.DisposedField.Equals(value) != true)) {
                    this.DisposedField = value;
                    this.RaisePropertyChanged("Disposed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Time {
            get {
                return this.TimeField;
            }
            set {
                if ((this.TimeField.Equals(value) != true)) {
                    this.TimeField = value;
                    this.RaisePropertyChanged("Time");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LogfileService.ILogfileService")]
    public interface ILogfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/ReadLogfiles", ReplyAction="http://tempuri.org/ILogfileService/ReadLogfilesResponse")]
        ProjectWebservices_Console.LogfileService.Logfile[] ReadLogfiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/ReadLogfiles", ReplyAction="http://tempuri.org/ILogfileService/ReadLogfilesResponse")]
        System.Threading.Tasks.Task<ProjectWebservices_Console.LogfileService.Logfile[]> ReadLogfilesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/DisposeAlarm", ReplyAction="http://tempuri.org/ILogfileService/DisposeAlarmResponse")]
        bool DisposeAlarm(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/DisposeAlarm", ReplyAction="http://tempuri.org/ILogfileService/DisposeAlarmResponse")]
        System.Threading.Tasks.Task<bool> DisposeAlarmAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/SendLogString", ReplyAction="http://tempuri.org/ILogfileService/SendLogStringResponse")]
        ProjectWebservices_Console.LogfileService.Logfile SendLogString(string txt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/SendLogString", ReplyAction="http://tempuri.org/ILogfileService/SendLogStringResponse")]
        System.Threading.Tasks.Task<ProjectWebservices_Console.LogfileService.Logfile> SendLogStringAsync(string txt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/ReadPendingAlarms", ReplyAction="http://tempuri.org/ILogfileService/ReadPendingAlarmsResponse")]
        ProjectWebservices_Console.LogfileService.Logfile[] ReadPendingAlarms();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/ReadPendingAlarms", ReplyAction="http://tempuri.org/ILogfileService/ReadPendingAlarmsResponse")]
        System.Threading.Tasks.Task<ProjectWebservices_Console.LogfileService.Logfile[]> ReadPendingAlarmsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/Log", ReplyAction="http://tempuri.org/ILogfileService/LogResponse")]
        bool Log(string id, string alarm, string name, string department, string apartment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogfileService/Log", ReplyAction="http://tempuri.org/ILogfileService/LogResponse")]
        System.Threading.Tasks.Task<bool> LogAsync(string id, string alarm, string name, string department, string apartment);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogfileServiceChannel : ProjectWebservices_Console.LogfileService.ILogfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogfileServiceClient : System.ServiceModel.ClientBase<ProjectWebservices_Console.LogfileService.ILogfileService>, ProjectWebservices_Console.LogfileService.ILogfileService {
        
        public LogfileServiceClient() {
        }
        
        public LogfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProjectWebservices_Console.LogfileService.Logfile[] ReadLogfiles() {
            return base.Channel.ReadLogfiles();
        }
        
        public System.Threading.Tasks.Task<ProjectWebservices_Console.LogfileService.Logfile[]> ReadLogfilesAsync() {
            return base.Channel.ReadLogfilesAsync();
        }
        
        public bool DisposeAlarm(string id) {
            return base.Channel.DisposeAlarm(id);
        }
        
        public System.Threading.Tasks.Task<bool> DisposeAlarmAsync(string id) {
            return base.Channel.DisposeAlarmAsync(id);
        }
        
        public ProjectWebservices_Console.LogfileService.Logfile SendLogString(string txt) {
            return base.Channel.SendLogString(txt);
        }
        
        public System.Threading.Tasks.Task<ProjectWebservices_Console.LogfileService.Logfile> SendLogStringAsync(string txt) {
            return base.Channel.SendLogStringAsync(txt);
        }
        
        public ProjectWebservices_Console.LogfileService.Logfile[] ReadPendingAlarms() {
            return base.Channel.ReadPendingAlarms();
        }
        
        public System.Threading.Tasks.Task<ProjectWebservices_Console.LogfileService.Logfile[]> ReadPendingAlarmsAsync() {
            return base.Channel.ReadPendingAlarmsAsync();
        }
        
        public bool Log(string id, string alarm, string name, string department, string apartment) {
            return base.Channel.Log(id, alarm, name, department, apartment);
        }
        
        public System.Threading.Tasks.Task<bool> LogAsync(string id, string alarm, string name, string department, string apartment) {
            return base.Channel.LogAsync(id, alarm, name, department, apartment);
        }
    }
}
